# Generated by Django 4.1.7 on 2023-03-13 17:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'Addon',
                'verbose_name_plural': 'Addons',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=650)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('unit', models.CharField(choices=[('g', 'Gram'), ('oz', 'Ounce (28 grams)'), ('lb', 'Pound (16 ounces)')], max_length=20)),
            ],
            options={
                'verbose_name': 'Weight',
                'verbose_name_plural': 'Weights',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='products/')),
                ('short_description', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('previous_price', models.FloatField()),
                ('effects', models.CharField(max_length=65)),
                ('may_relieve', models.CharField(max_length=150)),
                ('aromas', models.CharField(max_length=50)),
                ('addons', models.ManyToManyField(to='store.addon')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('composition', models.ManyToManyField(to='store.ingredient')),
                ('weights', models.ManyToManyField(to='store.weight')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
