# Generated by Django 4.1.7 on 2023-03-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='addons',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weights',
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(max_length=350),
        ),
        migrations.DeleteModel(
            name='Weight',
        ),
    ]
