# Generated by Django 4.1.7 on 2023-03-25 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aggregate_reviews',
            field=models.FloatField(auto_created=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
